### ISSUE TITLE
F# 5 and string interpolation

### ISSUE THREAD

**Issue by drhumlen** [JetBrains/fsharp-support#189]
With .NET 5 and F# 5 just around the corner (currently rc2, official release in November), what is the status for F# 5 support? Probably the biggest new feature is string interpolations. Is there a roadmap for F# 5 features support?

**Comment by auduchinok** [comment]
@drhumlen I've started working on updating FCS and changing needed pieces in the plugin.

**Comment by auduchinok** [comment]
It's implemented now.
