### ISSUE TITLE
ValueTuple type is missing in a new .NET Framework 4.7.1 project

### ISSUE THREAD

**Issue by vasily-kirichenko** [JetBrains/fsharp-support#2]
![image](https://user-images.githubusercontent.com/873919/32906200-3c768150-cb0d-11e7-959f-45bf2d45c4f3.png)

**Comment by auduchinok** [comment]
@vasily-kirichenko Thank you, fixed in 5a8c95ede26bb498b91688baccd4bb28c614f81d.
