### ISSUE TITLE
Pure open source IDE

### ISSUE THREAD

**Issue by ShalokShalom** [JetBrains/fsharp-support#21]
[This](https://github.com/JetBrains/fsharp-support/blob/master/README.md) README reads rather confusing to me: Is it possible to build fsharp support without Rider?

**Comment by vasily-kirichenko** [comment]
`cd <..>\fsharp-support\ReSharper.FSharp`
`msbuild ReSharper.FSharp.sln`

**Comment by ShalokShalom** [comment]
I am on Linux.

**Comment by ShalokShalom** [comment]
And Visual Studio is open source?

**Comment by vasily-kirichenko** [comment]
Then you need mono and xbuild I guess.

**Comment by auduchinok** [comment]
@ShalokShalom Yes, it is possible to build the Rider F# support plugin without using Rider, and it's [explicitly stated](https://github.com/JetBrains/fsharp-support/blob/master/README.md#requirements) in the readme that Rider is an optional tool to have.

You should have `dotnet` SDK installed which has `msbuild` bundled. To build the plugin you have to use 2.0 version or newer. `dotnet build ReSharper.FSharp.sln` should do the trick.

Are there any particular build steps that didn't work for you on Linux?

**Comment by ShalokShalom** [comment]
Yes, it is explicitly stated, just not explicitly stated described how to do. 

It is stated how to build Rider, see here: 
https://github.com/JetBrains/fsharp-support#building-the-plugin-and-launching-rider-in-a-sandbox

And then "`if using IntelliJ IDEA`" which gets compared to `Gradle`. 
Why?

I would more expect one way which describes how to build it with Rider and one how to build it with IntelliJ. 

I have not tried yet to build any of both, because I wanted to hint about this imho documentation issue.

**Comment by vasily-kirichenko** [comment]
The plugin consists of two parts: Intellij part (written in Kotlin) and Rider (.net) part, written in C#/F#. To build the plugin you need to build both parts. `gradlew prepare` downloads everything, `gradlew runIde` build the Kotlin part, downloads a Rider snapshot, copies .net part, installs the plugin into the test Rider and run it. Building ReSharper.FSharp.sln is needed in order to build .net part binaries.

**Comment by ShalokShalom** [comment]
So, how is this completely open source, if I need both parts? @auduchinok auduchinok says its possible without

**Comment by auduchinok** [comment]
@ShalokShalom I'm not sure what are you asking about? The plugin consists of two parts both of which are open-source with sources in this repo.

**Comment by ShalokShalom** [comment]
Ah, I see. So I use IDEA and the fsharp implementation of Rider in order to build. Thats fine. 

As said, the [README](https://github.com/JetBrains/fsharp-support#building-the-plugin-and-launching-rider-in-a-sandbox) has no header/title without "Rider" in its name and that one is closed source.

**Comment by auduchinok** [comment]
> As said, the README has no header/title without "Rider" in its name and that one is closed source.

If you want not to use Rider to build a Rider plugin I would recommend going with MSBuild from either Microsoft Build Tools or .NET Core SDK. Please use documentation for the tool of your choice.
