### ISSUE TITLE
Preserve newline in formatting

### ISSUE THREAD

**Issue by nojaf** [JetBrains/fsharp-support#24]
The settings panel of the latest Rider does not reflect all options of the latest fantomas build.

![image](https://user-images.githubusercontent.com/2621499/45688372-800ed180-bb51-11e8-8f88-52bc253db557.png)

It does not have support for [PreserveEndOfLine](https://github.com/fsprojects/fantomas/blob/master/docs/Documentation.md#using-the-api).

If you can explain how I can add the setting, I'm willing to pick this up. 
First guess is extending [settings in ReformatCode](https://github.com/JetBrains/fsharp-support/blob/6d0187bd87e4a13704ec5d24a9ce5d421499a8a4/ReSharper.FSharp/src/FSharp.Psi.Features/src/Formatter/ReformatCode.fs#L39) but how can I do that?

**Comment by auduchinok** [comment]
@nojaf Thank you for taking care of this. The new options can be added to the settings key here https://github.com/JetBrains/fsharp-support/blob/ecac866084a8492d4f80a5116ca6c47c70239dd1/ReSharper.FSharp/src/FSharp.Psi.Features/src/Formatter/FSharpCodeStylePage.fs#L18-L23

To add it to the settings page it should be added to the schema below in the same file: https://github.com/JetBrains/fsharp-support/blob/ecac866084a8492d4f80a5116ca6c47c70239dd1/ReSharper.FSharp/src/FSharp.Psi.Features/src/Formatter/FSharpCodeStylePage.fs#L84-L87

Adding options to these two places should be enough to use in the formatter code.

**Comment by auduchinok** [comment]
Fixed in be1b20e955bb535da4b5af3fd1b9b7456db8e82b.
