### ISSUE TITLE
F# 4.5 yield upcast "relaxation" change not working in Rider JetBrains Rider 2018.3 EAP 4?

### ISSUE THREAD

**Issue by bentayloruk** [JetBrains/fsharp-support#29]
F# 4.5 [relaxed the upcast requirements for yield in F# seq/list/array expressions](https://blogs.msdn.microsoft.com/dotnet/2018/08/14/announcing-f-4-5/).  We have some code that is taking advantage of this, but Rider is showing it as an error.

Below you can see a simple example of this issue (it's the code from the F# 4.5 announcement).  The lack of upcast shows as an error, but the project will build fine, so it appears to be an editor issue.

![image](https://user-images.githubusercontent.com/189409/47807263-8dfc6880-dd33-11e8-9ea1-fbd1012e43b5.png)

Not sure if I've missed a config option, or this is an issue.  My version details are:

```
JetBrains Rider 2018.3 EAP
Build #RD-183.3885.151, built on October 25, 2018
Rider EAP User
Expiration date: November 24, 2018
JRE: 1.8.0_152-release-1343-b12 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14
```

**Comment by auduchinok** [comment]
@bentayloruk We probably need to update our bundled FCS to get this feature, it's somewhat outdated.
Thank you for the report, I'll take care of it.

**Comment by jonasdw** [comment]
I'm having the same issue.

![image](https://user-images.githubusercontent.com/7934104/48694126-c4633000-ebdb-11e8-8560-b40688b7b55a.png)

`
JetBrains Rider 2018.2.3
Build #RD-182.4231.496, built on September 13, 2018
JRE: 1.8.0_152-release-1248-b8 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6
`

**Comment by auduchinok** [comment]
Fixed in https://github.com/JetBrains/fsharp-support/commit/aee2308d21b2ed7389affe8f79f64717480a7960.
