### ISSUE TITLE
Refactor is not available

### ISSUE THREAD

**Issue by plentylife** [JetBrains/fsharp-support#38]
Hello,

I'm trying to refactor some code in Rider 2018.3
When I try to rename a module, or a type, the option is grayed out.
![screenshot_20190209_131343](https://user-images.githubusercontent.com/31143124/52524619-d6012480-2c6c-11e9-9bf9-d522b7f411f6.png)
![screenshot_20190209_131428](https://user-images.githubusercontent.com/31143124/52524622-d8fc1500-2c6c-11e9-84c7-7d3b745f34fd.png)

Am I doing something wrong?
I am able to rename local variables

![screenshot_20190209_131459](https://user-images.githubusercontent.com/31143124/52524623-dc8f9c00-2c6c-11e9-80f1-5f6e77b713a6.png)

**Comment by vasily-kirichenko** [comment]
Currently Rename refactoring works on local bindings only. AFAIK @auduchinok is working on making it work on all symbols.

**Comment by plentylife** [comment]
Oh, thank you. That's unexpected.
Is support for F# fairly low right now in general?

**Comment by auduchinok** [comment]
@plentylife Rename is going to be available in upcoming 2019.1 EAP builds and nightlies when they become public.

**Comment by plentylife** [comment]
Thank you for all your hard work!

**Comment by auduchinok** [comment]
Rename is now available in 2019.1 EAP builds, please try it out. If you encounter case where it doesn't work, please create a separate issue (preferably on [our tracker](https://youtrack.jetbrains.com/issues/RIDER) if you have an account there).
