### ISSUE TITLE
Question: Jetbrains.Fantomas

### ISSUE THREAD

**Issue by nojaf** [JetBrains/fsharp-support#4]
I just found [this](https://www.nuget.org/packages/JetBrains.Fantomas/) on nuget and was wondering if it can be used outside of Rider?
A while ago I read that fantomas [might end up in FSharp.Compiler.Service](https://github.com/dungpa/fantomas/issues/125).
So now I'm curious where the team is heading with the usage of Fantomas. Will you eventually swap to the FCS version once it is stable? 

On a side note is the formatting of F# code already available in Rider 2017.2?

**Comment by auduchinok** [comment]
@nojaf It is a version built against latest FCS, nothing is added, something not needed in our case is cut. This package should have been unlisted in NuGet, although technically it could be used outside Rider if a newer FCS is needed. A better approach would be to open a PR incorporating changes needed for the newer FCS in the Fantomas repo and ask its maintainers to publish a newer build to NuGet. I'm going to do it at some point if no one else does it before.
We'll definitely move to the Fantomas bundled in FCS once it's integrated (see a newer discussion [here](https://github.com/Microsoft/visualfsharp/pull/3542)), but looking at the discussion I doubt it'll happen soon.

As of Rider 2017.2.1 selection formatting was disabled but should work for file level in cases where Fantomas is able to reformat it.

**Comment by nojaf** [comment]
Thanks for the clarification. I tested the formatting on a file instead of selection, it indeed works.
