### ISSUE TITLE
Error tooltip hides all other information

### ISSUE THREAD

**Issue by TeaDrivenDev** [JetBrains/fsharp-support#57]
Hovering over code with a compiler error only shows the error text and hides all other information, like function signatures and inferred types. This makes it a lot more difficult to find the actual cause of the error and fix it. Visual Studio and Ionide used to do that too, but now show both the normal information and the error in one tooltip, so all necessary data should actually be available from the compiler.

Rider:
![image](https://user-images.githubusercontent.com/2247219/62476401-351c9d80-b7a7-11e9-9424-fe8dafb95838.png)

VS:
![image](https://user-images.githubusercontent.com/2247219/62476448-4c5b8b00-b7a7-11e9-9ef4-066c8091b421.png)

**Comment by auduchinok** [comment]
There's everything ready on F# plugin side. The signature tooltips, however, are currently being hidden in the platform code that looks at higher severity of warnings/errors here.

There're issues in both Rider and IntelliJ projects on YouTrack. [IDEA-189703](https://youtrack.jetbrains.com/issue/IDEA-189703) is now considered fixed and its results look very promising to me. This is one of the screenshots I've seen:

![image (21)](https://user-images.githubusercontent.com/3923587/62477716-31dadf00-b7b2-11e9-9028-f8865adcde39.png)

Please vote for [RIDER-6237](https://youtrack.jetbrains.com/issue/RIDER-6237) to get updates on when we're able to use it in Rider too.

**Comment by auduchinok** [comment]
It has been fixed in 2020.1, sorry for the late update here. 🙂 
<img width="246" alt="Screenshot 2020-09-22 at 14 24 41" src="https://user-images.githubusercontent.com/3923587/93876357-62941580-fcdf-11ea-820e-ab752bef0748.png">
