### ISSUE TITLE
[rename refactor] single case DU matching DU name could optionally be renamed

### ISSUE THREAD

**Issue by smoothdeveloper** [JetBrains/fsharp-support#59]
Considering this code:
```fsharp
type SingleCaseDU = 
    | SingleCaseDU of obj
    static member getValue = function | SingleCaseDU o -> o
```

I'd like the rename refactor to optionally propose to rename the single case named `SingleCaseDU ` the same.

**Comment by auduchinok** [comment]
@smoothdeveloper This is a great idea! It's really easy to always rename the only union case or a union with a single case. It is a bit harder to make it being renamed optional, though. I'll take a look, thanks!

**Comment by auduchinok** [comment]
@smoothdeveloper Do you think it should also be suggested when the both symbols had different names before renaming?

The whole infrastructure is there in ReSharper so it was quite easy to get it working.

<img width="553" alt="Screenshot 2019-08-18 at 15 37 37" src="https://user-images.githubusercontent.com/3923587/63224527-246c1e80-c1ce-11e9-9113-ab96cd3f7508.png">

**Comment by smoothdeveloper** [comment]
@auduchinok, exciting!

I have no strong opinion, maybe option to specify both names at once (user retain full control, defaults would be single case with same name gets both renamed)?

Do you see opportunity to compose a dialog with the list of all cases for batch renaming if this one prove successful?

**Comment by auduchinok** [comment]
According to the text above the suggestions table the names of related symbols can be modified and they indeed are!
We can try to always provide the suggestions and to see if there're any complaints about them getting in the way in 2019.3 EAP/release.

<img width="552" alt="Screenshot 2019-08-18 at 16 21 35" src="https://user-images.githubusercontent.com/3923587/63224971-508a9e00-c1d4-11e9-9dc0-f128667538a3.png">

**Comment by auduchinok** [comment]
> Do you see opportunity to compose a dialog with the list of all cases for batch renaming if this one prove successful?
Can you share an example where changing all names at once could be more useful than doing renames separately?

**Comment by auduchinok** [comment]
@smoothdeveloper Thank again for the idea, I'm closing the issue as it's was implemented in https://github.com/JetBrains/fsharp-support/commit/4965eb79d16974e6954626b4f0963914af701408. By all means share your thoughts about multi-case unions if you find such rename to be useful.

**Comment by smoothdeveloper** [comment]
> Can you share an example where changing all names at once could be considerably more useful than doing renames separately?

I'm just considering workflow with several simple refactor in a row, I know issuing refactor sequentially generally takes time in larger solution.

When doing rename on the top level identifier of a DU, if we can batch more changes in the editing, it would make it better, but I get that the rename workflow should be lean in terms of input (f2, type new name, enter, does what user expects 99%) and adding complexity to the dialog may not be fitting the product.

Imagining user doing a bunch of renames in fsharp typed AST DU versus issuing them separately, could be a nice stress testing benchmark.

Looking forward to try the next EAP ! :+1:
