### ISSUE TITLE
fsx scripting doesn't use the correct FSharp.Core in the editor

### ISSUE THREAD

**Issue by smoothdeveloper** [JetBrains/fsharp-support#60]
When I edit a .fsx with this code, it doesn't seem to bind to version of FSharp.Core having `Result` type and `Option.defaultValue`.
```fsharp
let ok =
    Ok 1
    |> Result.mapError (fun _ -> Unchecked.defaultof<string>)

let v = Some 1
let r = v |> Option.defaultValue 3
```

![image](https://user-images.githubusercontent.com/87944/63685265-30c02f00-c7ff-11e9-81f7-f4eff97e0d9f.png)

build settings:
![image](https://user-images.githubusercontent.com/87944/63685404-7ed53280-c7ff-11e9-8039-ea82de9ee3be.png)

fsi settings:
![image](https://user-images.githubusercontent.com/87944/63685440-94e2f300-c7ff-11e9-892e-44ab65997cf7.png)

**Comment by auduchinok** [comment]
@smoothdeveloper Thank you for the report. It seems to have been fixes with some FCS/FSharp.Core update before.
<img width="511" alt="Screenshot 2019-12-24 at 15 25 37" src="https://user-images.githubusercontent.com/3923587/71413115-c52d8780-2661-11ea-8add-04927b9b15d7.png">
