### ISSUE TITLE
F# 4.7 support

### ISSUE THREAD

**Issue by drhumlen** [JetBrains/fsharp-support#63]
Good code red. F# 4.7 has relaxed some of its syntax, and `yield`s are now (often) implicit.

You're probably already working on it, but I just thought I'd create an issue for it.

**Comment by auduchinok** [comment]
Yes, I'm migrating FCS right now.

**Comment by nojaf** [comment]
Would that be compatible with FCS 32?

**Comment by vasily-kirichenko** [comment]
@nojaf what is FCS 32?..

**Comment by nojaf** [comment]
@vasily-kirichenko https://www.nuget.org/packages/FSharp.Compiler.Service/32.0.0

**Comment by auduchinok** [comment]
@nojaf Chances it would, as I've rebased to a roughly the same state of `master` FCS branch as the 32 release, but we may end up with a somewhat newer commit (which FCS will eventually get too). I think it should be compatible for Fantomas needs in any case.

**Comment by nojaf** [comment]
Great, will this end up in the net193 branch?

**Comment by auduchinok** [comment]
Yes, it's the current default branch and we will branch for 2019.3 EAPs/release from it.

**Comment by drhumlen** [comment]
F# 4.7 seems to be working very well since the release of 2019.3 🎉

I'm closing the issue(?).

**Comment by auduchinok** [comment]
Yes, indeed. We've updated FSharp.Compiler.Service to a version that have F# 4.7 support.
I was going to close the issue after updating the release notes. :)
